### ISSUE TITLE
sse test timeout error

### ISSUE THREAD

**Issue by xuzexin-hz** [modelcontextprotocol/inspector#240]
**Describe the bug**
![Image](https://github.com/user-attachments/assets/5c416588-494e-4f00-8550-ff39a0edda37)
I found the inspector problem. In the above picture, there is a timeout mechanism in both places 1 and 2. The default timeout in place 1 is 60 seconds, and the default timeout in place 2 is 10 seconds. http://localhost:5173/?timeout=60000 can solved the timeout mechanism in place 2 by accessing it this way, but place 1 still times out.
**To Reproduce**
1. The sse server provides a method that takes more than 60 seconds

code:
# server.py
import asyncio
import time

from mcp.server.fastmcp import FastMCP

mcp = FastMCP("Demo")

@mcp.tool()
async def add(a: int, b: int) -> int:
    # await asyncio.sleep(5) # work well
    await asyncio.sleep(66)  # error
    return a + b
if __name__ == "__main__":
    mcp.run(transport="sse")

**Comment by cliffhall** [comment]
> I tried putting this to 60000 but I'm still getting a weird loop:

this is probably fixed with #259 which will be in a 0.8.1 release, going out today or tomorrow. 

Until that release you could clone this repo, build, and start then try against your server to see if it persists.

**Comment by 0xTomDaniel** [comment]
> > I tried putting this to 60000 but I'm still getting a weird loop:
> 
> [@fygure](https://github.com/fygure) this is probably fixed with [#259](https://github.com/modelcontextprotocol/inspector/pull/259) which will be in a 0.8.1 release, going out today or tomorrow.
> 
> Until that release you could clone this repo, build, and start then try against your server to see if it persists.

Did the `Configuration` button actually make it into 0.8.1 release because I didn't see it mentioned in the release notes?

**Comment by cliffhall** [comment]
> > > I tried putting this to 60000 but I'm still getting a weird loop:
> > 
> > 
> > [@fygure](https://github.com/fygure) this is probably fixed with [#259](https://github.com/modelcontextprotocol/inspector/pull/259) which will be in a 0.8.1 release, going out today or tomorrow.
> > Until that release you could clone this repo, build, and start then try against your server to see if it persists.
> 
> Did the `Configuration` button actually make it into 0.8.1 release because I didn't see it mentioned in the release notes?

It's in [0.8.0](https://github.com/modelcontextprotocol/inspector/releases/tag/0.8.0).

**Comment by xuzexin-hz** [comment]
There seems to be a problem. Look at the code to get the timeout value of const DEFAULT_REQUEST_TIMEOUT_MSEC = 6e4;. You can test it with the server code I gave above. The problem still exists.

**Comment by pulkitsharma07** [comment]
If you can run inspector locally from `main`, please try now, this should be fixed  post https://github.com/modelcontextprotocol/inspector/pull/271

**Comment by xuzexin-hz** [comment]
Sorry, it was my fault. Now it is ok, I want to run the source code main branch.
    Thanks
